# Generated by Django 3.1.4 on 2020-12-21 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('set_part', models.CharField(choices=[('Głowa', 'Głowa'), ('Klata', 'Klata'), ('Nogi', 'Nogi'), ('Broń jednoręczna', 'Broń jednoręczna'), ('Broń dwuręczna', 'Broń dwuręczna'), ('Druga broń', 'Druga broń')], max_length=20)),
                ('pasives', models.ManyToManyField(to='ajversh.Pasive')),
                ('spells', models.ManyToManyField(to='ajversh.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_build', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Dungi Grupowe', 'Dungi Grupowe'), ('Dungi Solo', 'Dungi Solo'), ('PVP', 'PVP'), ('ZVZ', 'ZVZ'), ('AVALON', 'AVALON')], max_length=50, null=True)),
                ('boots', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_item', to='ajversh.item')),
                ('boots_tier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_tier', to='ajversh.tier')),
                ('chest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_item', to='ajversh.item')),
                ('chest_tier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_tier', to='ajversh.tier')),
                ('hand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_item', to='ajversh.item')),
                ('hand_tier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_tier', to='ajversh.tier')),
                ('head', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_item', to='ajversh.item')),
                ('head_tier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tier', to='ajversh.tier')),
                ('second_hand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_hand_item', to='ajversh.item')),
                ('second_hand_tier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_hand_tier', to='ajversh.tier')),
            ],
        ),
    ]
