# Generated by Django 3.1.4 on 2021-01-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='pasive')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='spell')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4.1', '4.1'), ('4.2', '4.2'), ('4.3', '4.3'), ('5.1', '5.1'), ('5.2', '5.2'), ('5.3', '5.3'), ('6.1', '6.1'), ('6.2', '6.2'), ('6.3', '6.3'), ('7.1', '7.1'), ('7.2', '7.2'), ('7.3', '7.3'), ('8.1', '8.1'), ('8.2', '8.2'), ('8.3', '8.3')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='items')),
                ('set_part', models.CharField(choices=[('Głowa', 'Głowa'), ('Klata', 'Klata'), ('Nogi', 'Nogi'), ('Broń jednoręczna', 'Broń jednoręczna'), ('Bron dwureczna', 'Bron dwureczna'), ('Druga broń', 'Druga broń')], max_length=20)),
                ('d', models.ManyToManyField(blank=True, related_name='d_spell', to='ajversh.Spell')),
                ('e', models.ManyToManyField(blank=True, related_name='e_spell', to='ajversh.Spell')),
                ('f', models.ManyToManyField(blank=True, related_name='f_spell', to='ajversh.Spell')),
                ('pasives', models.ManyToManyField(blank=True, to='ajversh.Pasive')),
                ('q', models.ManyToManyField(blank=True, related_name='q_spell', to='ajversh.Spell')),
                ('r', models.ManyToManyField(blank=True, related_name='r_spell', to='ajversh.Spell')),
                ('w', models.ManyToManyField(blank=True, related_name='w_spell', to='ajversh.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_build', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Dungi Grupowe', 'Dungi Grupowe'), ('Dungi Solo', 'Dungi Solo'), ('PVP', 'PVP'), ('ZVZ', 'ZVZ'), ('AVALON', 'AVALON')], max_length=50, null=True)),
                ('boots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_item', to='ajversh.item')),
                ('boots_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_tier', to='ajversh.tier')),
                ('chest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_item', to='ajversh.item')),
                ('chest_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_tier', to='ajversh.tier')),
                ('hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_item', to='ajversh.item')),
                ('hand_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_tier', to='ajversh.tier')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_item', to='ajversh.item')),
                ('head_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tier', to='ajversh.tier')),
                ('off_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_hand_item', to='ajversh.item')),
                ('off_hand_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_hand_tier', to='ajversh.tier')),
            ],
        ),
    ]
