# Generated by Django 3.1.4 on 2021-02-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='pasive')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='spell')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TankPasive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='pasive')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='items')),
                ('set_part', models.CharField(choices=[('Głowa', 'Głowa'), ('Klata', 'Klata'), ('Nogi', 'Nogi'), ('Broń jednoręczna', 'Broń jednoręczna'), ('Broń dwuręczna', 'Broń dwuręczna'), ('Druga ręka', 'Druga ręka')], max_length=20)),
                ('type_material', models.CharField(blank=True, choices=[('Materiał', 'Materiał'), ('Skóra', 'Skóra'), ('Płyta', 'Płyta')], max_length=20)),
                ('d', models.ManyToManyField(blank=True, related_name='d_spell', to='ajversh.Spell')),
                ('e', models.ManyToManyField(blank=True, related_name='e_spell', to='ajversh.Spell')),
                ('f', models.ManyToManyField(blank=True, related_name='f_spell', to='ajversh.Spell')),
                ('pasives', models.ManyToManyField(blank=True, related_name='pasive', to='ajversh.Pasive')),
                ('q', models.ManyToManyField(blank=True, related_name='q_spell', to='ajversh.Spell')),
                ('r', models.ManyToManyField(blank=True, related_name='r_spell', to='ajversh.Spell')),
                ('tank_pasives', models.ManyToManyField(blank=True, related_name='tank_pasive', to='ajversh.TankPasive')),
                ('w', models.ManyToManyField(blank=True, related_name='w_spell', to='ajversh.Spell')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_build', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Grupowe Dungi', 'Grupowe Dungi'), ('Solo Dungi', 'Solo Dungi'), ('PVP', 'PVP'), ('ZVZ', 'ZVZ'), ('AVALON', 'AVALON')], max_length=50, null=True)),
                ('role_set', models.CharField(choices=[('Tank', 'Tank'), ('Heal', 'Heal'), ('MDPS', 'MDPS'), ('RDPS', 'RDPS'), ('Supp', 'Supp')], max_length=20, null=True)),
                ('boots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_item', to='ajversh.item')),
                ('boots_pasive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_pasive', to='ajversh.pasive')),
                ('boots_spell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_spell', to='ajversh.spell')),
                ('chest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_item', to='ajversh.item')),
                ('chest_pasive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_pasive', to='ajversh.pasive')),
                ('chest_pasive_tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_pasive_tank', to='ajversh.tankpasive')),
                ('chest_spell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_spell', to='ajversh.spell')),
                ('hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_item', to='ajversh.item')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_item', to='ajversh.item')),
                ('head_pasive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_pasive', to='ajversh.pasive')),
                ('head_spell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_spell', to='ajversh.spell')),
                ('off_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_hand_item', to='ajversh.item')),
                ('weapon_pasive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_pasive', to='ajversh.pasive')),
                ('weapon_spell_e', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_spell_e', to='ajversh.spell')),
                ('weapon_spell_q', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_spell_q', to='ajversh.spell')),
                ('weapon_spell_w', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_spell_w', to='ajversh.spell')),
            ],
        ),
    ]
