# Generated by Django 3.1.4 on 2021-02-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
