# Generated by Django 3.1.4 on 2020-12-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='boots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_item', to='ajversh.item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='boots_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_tier', to='ajversh.tier'),
        ),
        migrations.AlterField(
            model_name='build',
            name='chest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_item', to='ajversh.item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='chest_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_tier', to='ajversh.tier'),
        ),
        migrations.AlterField(
            model_name='build',
            name='hand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_item', to='ajversh.item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='hand_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_tier', to='ajversh.tier'),
        ),
        migrations.AlterField(
            model_name='build',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_item', to='ajversh.item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='head_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_tier', to='ajversh.tier'),
        ),
        migrations.AlterField(
            model_name='build',
            name='second_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_hand_item', to='ajversh.item'),
        ),
        migrations.AlterField(
            model_name='build',
            name='second_hand_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_hand_tier', to='ajversh.tier'),
        ),
    ]
