# Generated by Django 3.1.4 on 2021-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pasives',
            field=models.ManyToManyField(blank=True, related_name='pasive', to='ajversh.Pasive'),
        ),
    ]
