# Generated by Django 3.1.4 on 2021-01-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0002_auto_20201227_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/items/'),
        ),
    ]
