# Generated by Django 3.1.4 on 2021-02-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0002_categorybuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajversh.categorybuild'),
        ),
        migrations.AlterField(
            model_name='categorybuild',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
