# Generated by Django 3.1.4 on 2021-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0002_auto_20210123_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='set_part',
            field=models.CharField(choices=[('Głowa', 'Głowa'), ('Klata', 'Klata'), ('Nogi', 'Nogi'), ('Broń jednoręczna', 'Broń jednoręczna'), ('Broń dwuręczna', 'Broń dwuręczna'), ('Druga ręka', 'Druga ręka')], max_length=20),
        ),
    ]
