# Generated by Django 3.1.4 on 2021-01-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0003_auto_20210123_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='boots_tier',
        ),
        migrations.RemoveField(
            model_name='build',
            name='chest_tier',
        ),
        migrations.RemoveField(
            model_name='build',
            name='hand_tier',
        ),
        migrations.RemoveField(
            model_name='build',
            name='head_tier',
        ),
        migrations.RemoveField(
            model_name='build',
            name='off_hand_tier',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
