# Generated by Django 3.1.4 on 2021-01-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0003_auto_20210105_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
    ]
