# Generated by Django 3.1.4 on 2021-01-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0004_auto_20210125_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='boots_pasive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_pasive', to='ajversh.pasive'),
        ),
        migrations.AddField(
            model_name='build',
            name='boots_spell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_spell', to='ajversh.spell'),
        ),
        migrations.AddField(
            model_name='build',
            name='chest_pasive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_pasive', to='ajversh.pasive'),
        ),
        migrations.AddField(
            model_name='build',
            name='chest_spell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_spell', to='ajversh.spell'),
        ),
        migrations.AddField(
            model_name='build',
            name='head_pasive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_pasive', to='ajversh.pasive'),
        ),
        migrations.AddField(
            model_name='build',
            name='head_spell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_spell', to='ajversh.spell'),
        ),
        migrations.AddField(
            model_name='build',
            name='weapon_pasive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_pasive', to='ajversh.pasive'),
        ),
        migrations.AddField(
            model_name='build',
            name='weapon_spell_e',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_spell_e', to='ajversh.spell'),
        ),
        migrations.AddField(
            model_name='build',
            name='weapon_spell_q',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_spell_q', to='ajversh.spell'),
        ),
        migrations.AddField(
            model_name='build',
            name='weapon_spell_w',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_spell_w', to='ajversh.spell'),
        ),
    ]
