# Generated by Django 3.1.4 on 2021-01-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0004_auto_20210105_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pasives',
            field=models.ManyToManyField(blank=True, to='ajversh.Pasive'),
        ),
        migrations.AlterField(
            model_name='item',
            name='spells',
            field=models.ManyToManyField(blank=True, to='ajversh.Spell'),
        ),
        migrations.AlterField(
            model_name='pasive',
            name='img',
            field=models.ImageField(blank=True, upload_to='pasive'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='img',
            field=models.ImageField(blank=True, upload_to='spell'),
        ),
    ]
