# Generated by Django 3.1.4 on 2021-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0005_auto_20210126_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='role_set',
            field=models.CharField(choices=[('Tank', 'Tank'), ('Heal', 'Heal'), ('MDPS', 'MDPS'), ('RDPS', 'RDPS'), ('Supp', 'Supp')], max_length=20, null=True),
        ),
    ]
