# Generated by Django 3.1.4 on 2021-01-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0006_build_role_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='category',
            field=models.CharField(choices=[('Grupowe Dungi', 'Grupowe Dungi'), ('Solo Dungi', 'Solo Dungi'), ('PVP', 'PVP'), ('ZVZ', 'ZVZ'), ('AVALON', 'AVALON')], max_length=50, null=True),
        ),
    ]
