# Generated by Django 3.1.4 on 2021-01-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0007_auto_20210126_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type_material',
            field=models.CharField(blank=True, choices=[('Materiał', 'Materiał'), ('Skóra', 'Skóra'), ('Płyta', 'Płyta')], max_length=20),
        ),
    ]
