# Generated by Django 3.1.4 on 2021-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0009_item_tank_pasives'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankPasive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='pasive')),
                ('description', models.TextField()),
            ],
        ),
    ]
