# Generated by Django 3.1.4 on 2021-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0010_tankpasive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tank_pasives',
            field=models.ManyToManyField(blank=True, related_name='tank_pasive', to='ajversh.TankPasive'),
        ),
    ]
