# Generated by Django 3.1.4 on 2021-01-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0011_auto_20210129_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tank_pasives',
        ),
    ]
