# Generated by Django 3.1.4 on 2021-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0012_remove_item_tank_pasives'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tank_pasives',
            field=models.ManyToManyField(blank=True, related_name='tank_pasive', to='ajversh.TankPasive'),
        ),
    ]
