# Generated by Django 3.1.4 on 2021-01-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajversh', '0013_item_tank_pasives'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='chest_pasive_tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chest_pasive_tank', to='ajversh.tankpasive'),
        ),
    ]
